### PR TITLE
change ctrl-u and ctrl-d to u and d

### PR DESCRIPTION
**Pull request by TangMonk**
#72

### CODE REVIEW

**Comment by gggritso** [comment]
Thank you for the PR, the code looks good to me. I’m going to leave this open for a little while to make sure that no one has any complaints before merging. I don’t want to break things for people, so I might wrap this up in a setting.

**Comment by jpulgarin** [comment]
I would prefer for the shortcut to remain as is so as to emulate Vim behaviour.

**Comment by DArtagan** [comment]
I'm personally inclined to make "d" close the tab.  Too bold to open such a PR?

**Comment by gggritso** [comment]
Maybe too bold! I don’t know about you all, but I pretty often get confused because I press `t` or `r` by accident and my page doesn’t do what I thought it might.

**Comment by karimknaebel** [comment]
So what do you think?

**Comment by gggritso** [comment]
This project is officially abandonware and is not accepting any PRs or issues. This extension will stop working as of macOS Catalina. Sorry, and thank you, but mostly sorry!

**Pull request closed without merging**
