### PR TITLE
Add useful example blacklist URL as default value

### PR DESCRIPTION
**Pull request by dwaxe**
Gmail is probably the most commonly blacklisted URL by browser-vim extension users. It's default on many other browser-vim extensions.

### CODE REVIEW

**Comment by dwaxe** [comment]
I added Facebook as well to make it extra clear how to add new blacklist sites (separated by comma without spaces).

**Comment by gggritso** [comment]
Values for this setting are parsed as regular expressions, so the suggested values might not work since regexp operators in them are not escaped (you’d have to use something like `:\/\/mail.google.com\/*`). Also, I personally use Vimmy shortcuts on Facebook, so I’m a little hesitant to add that one. How about `mail.google.com,slack.com` for the value?

**Comment by dwaxe** [comment]
Should we parse the strings directly as regular expressions? I could change it to the more "natural" treatment of urls like other browser-vim extensions so users don't have to worry about escaping characters. My worry with `mail.google.com` is urls with the string in its parameters for some reason. Admittedly this rarely occurs, but Vimium makes it even more explicit for safety, e.g. `https?://mail.google.com/*`. Maybe that amount of safety is useful?

**Comment by gggritso** [comment]
I agree with your point about `mail.google.com` appearing elsewhere in the URL, even though I think it’s unlikely. I figured that allowing regular expressions is the most flexible thing, and anyone using this feature would be welcome to come here for help. It sounds like you’re thinking about a subset of regular expressions, allowing for wildcards, is that right? If so, what wildcards would be allowed, just `?` and `*`?

**Pull request closed without merging**
