### PR TITLE
support page history traversal

### PR DESCRIPTION
**Pull request by kujohn**

### CODE REVIEW

**Comment by gggritso** [comment]
First and foremost, thank you so much for the PR! I personally like it a lot, but I want to get some feedback from other users, if possible. Namely:
- is it okay that `shift-h` and `shift-l` do something very different here as opposed to in Vim?
- do we want to add these shortcuts even though `cmd-[` and `cmd-]` accomplish the same thing?
- would the shortcuts `ctrl-i` and `ctrl-o` be more appropriate, since they jump back and forth between locations, which is somewhat similar?

As I said, I personally don’t mind this. If there are no objections within a few days, I’ll merge it in. In the meantime, could you please add a note about the new command to the `README`?

**Comment by kujohn** [comment]
Yeah, totally. I was just used to the `shift-h/l` in vimium on chrome. Perhaps it should be better as a choice for the user to pick from.

**Comment by dbmrq** [comment]
I like the `<c-i>` and `<c-o>` idea. Another option is `u` and `<c-r>`… in a browser going back and forward are the closest things to unoing and redoing I think. And just `u` is pretty easy to type for going back, which is more usual than going forward. Any of these options would be fine by me though, even `<s-h>` and `<s-l>`.

**Comment by kujohn** [comment]
`ctrl-i` and `ctrl-o` feels good too. They are good options either way and much better than using `cmd-[/]`. At least to me, I like to stay in `vim` mode and switching to using os x shortcuts is an overhead in my tiny little brain. 😃

**Comment by bramkok** [comment]
> [...] is it okay that shift-h and shift-l do something very different here as opposed to in Vim?

My preference for `shift-h` and `shift-l` also comes from using vimium for years on Chrome. However, using mind over muscle memory, I think it's better to have a strict set of Vim key bindings as opposed to having some pieced together key salad.

Ideally we would have original `vim` key mappings set as defaults and settings available to satisfy personal preferences. Wouldn't that be a better solution?

**Comment by gggritso** [comment]
The fact that `shift+l` and `shift-h` are the Vimium equivalent is a _very_ strong vote. Since Vim doesn't have the concept of a history, and Vimmy doesn't have the concept of a cursor (at least not the way that Vim does) there's no point trying to find a direct-ish equivalent. I think `shift-l` and `shift-h` are the way to go.

**Comment by dbmrq** [comment]
Why not just `h` and `l` then? Left and right for back and forth makes sense, but `<s-h>` and `<s-l>` go to the top and to the bottom in Vim.

**Comment by gggritso** [comment]
I think that `hjkl`_does_ have a direct equivalent in Safari. `jk` scroll up and down, `hl` should scroll left and right, no? I think that those four keys are _so_ ingrained that having two of them do something drastically different would be pretty strange.

**Comment by dbmrq** [comment]
Ah, I see. Ok then, sounds good. :)

**Comment by gggritso** [comment]
@kujohn Thank you for this PR, this is great 👌

**Comment by kujohn** [comment]
np 😄. Excellent extension btw!

**Pull request merged**
